# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BeautifyExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeautifyExample

  target 'BeautifyExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

   pod 'AgoraRtcEngine_iOS', '4.2.1'
   pod 'Masonry', '1.1.0'
   pod 'SVProgressHUD', '2.2.5'

end


post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
         end
    end
  end
end
